"""Add ChatMessage for chat history

Revision ID: 8de7ca483007
Revises: e6e06c122cbe
Create Date: 2025-06-23 23:42:56.876842

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8de7ca483007"
down_revision = "e6e06c122cbe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("sender", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat_message")
    # ### end Alembic commands ###
